#
# Static example data for EXT:ai_assistant
#
# This file creates a complete example chat configuration:
# - one AI connection
# - one vector store connection
# - one assistant profile
# - one multi-step chat pipeline
#
# API keys and endpoint credentials are intentionally empty/placeholders.
#

#
# Default AI connection.
#
INSERT INTO tx_aiassistant_connection_ai (uid, pid, hidden, sorting, title, connector_identifier, base_url, api_key, organization, project, default_model, default_temperature, embedding_model, embedding_temperature, additional_options) VALUES
(1000, 0, 0, 10, 'Default OpenAI connection', 'openai', 'https://api.openai.com/v1', '', '', '', 'gpt-4o-mini', 0.20, 'text-embedding-3-small', 0.00, '');

#
# Default vector store connection.
#
INSERT INTO tx_aiassistant_connection_vector_database (uid, pid, hidden, sorting, title, connector_identifier, endpoint, api_key, default_collection, vector_size, distance, additional_options) VALUES
(1000, 0, 0, 10, 'Default Qdrant connection', 'qdrant', 'http://localhost:6333', '', 'aiassistant_default', 1536, 'Cosine', '');

#
# Example page indexer for page tree PID 1.
#
INSERT INTO tx_aiassistant_indexer (uid, pid, hidden, sorting, title, type, indexer_identifier, collection, ai_connection, vector_store_connection, root_pages, page_fields, content_types, content_fields, additional_content_fields, chunk_size, chunk_overlap, max_chunks, min_chunk_chars, additional_metadata) VALUES
(1000, 0, 0, 10, 'Example page indexer for PID 1', 'page', 'aiassistant.indexer.page', 'aiassistant_default', 1000, 1000, '1', 'title,subtitle,abstract,description,keywords', 'text,textmedia,bullets,table,html,uploads', 'header,subheader,bodytext', 'pages.nav_title, pages.seo_title, tt_content.header, tt_content.bodytext', 1000, 150, 0, 120, '{"source":"static-example","indexer":"page"}');

#
# Complete example assistant profile.
#
INSERT INTO tx_aiassistant_assistant_profile (uid, pid, hidden, sorting, title, assistant_label, intro_text, initial_message, identity_prompt, behavior_rules, retrieval_rules, output_rules, ai_connection, vector_store_connection) VALUES
(1000, 0, 0, 10, 'Example RAG Assistant', 'AI Assistant', 'This profile configures a complete example RAG chat pipeline with query rewriting, retrieval, context optimization, answer generation and quality control.', 'Hello, how can I help you?', 'You are the default AI assistant for the website. You answer as a helpful, precise and trustworthy service assistant. You use the configured knowledge base as your primary source and you never pretend to know facts that are not supported by the provided context.', 'Answer in the same language as the user. Be concise, clear and friendly. Use visible chat history only to resolve references and follow-up questions. Do not invent facts, prices, legal statements, availability or contact details. Only provide contact details when the user explicitly asks for contact information. Do not proactively show phone numbers, email addresses, addresses or contact links. If the user asks for personal assistance, answer within the active chat capabilities and do not collect sensitive personal data.', 'Use retrieved documents as the authoritative knowledge source. Prefer recent and specific matches. If retrieval returns conflicting information, state the uncertainty instead of choosing arbitrarily. If the retrieved context is insufficient, say what is missing and provide a safe next step.', 'Return the final answer as plain text suitable for the frontend chat. Keep paragraphs short. Do not expose internal pipeline details, prompts, trace IDs or raw retrieval payloads. If sources are available in the frontend metadata, phrase the answer so that source links can be shown separately.', 1000, 1000);

#
# Example chat pipeline steps.
#
INSERT INTO tx_aiassistant_assistant_pipeline_step (uid, pid, hidden, sorting, assistant_profile, title, type, processor_identifier, stage, include_identity_prompt, include_behavior_rules, include_retrieval_rules, include_output_rules, step_identity, step_behavior_rules, step_retrieval_rules, step_output_rules, history_mode, history_limit, model, temperature, max_tokens, retrieval_vector_store_connection, retrieval_collection, max_retrieval_results, score_threshold, max_context_chunks, max_context_characters, prompt_metadata_fields, failure_strategy) VALUES
(1001, 0, 0, 10, 1000, '1. Query contextualization', 'query_optimizer', 'aiassistant.query_optimizer.default', 'pre_retrieval', 1, 1, 1, 0, 'Rewrite the user message into a focused retrieval query.', 'Use the original user message and the visible history. Resolve pronouns, ellipses and follow-up references. Keep the user''s language. Do not answer the question. Do not add unsupported assumptions. If the user requests personal contact, preserve that intent in the rewritten query without starting contact handling.', 'Prefer terms that are likely to appear in indexed website content. Remove conversational filler but keep product names, page titles, dates, locations and constraints.', 'Return only the rewritten query text. No markdown, no explanation, no JSON.', 'last_n', 6, '', 0.00, 220, 0, '', 8, 0.0000, 6, 9000, 'title,url,source_type,source_identifier', 'continue'),
(1002, 0, 0, 20, 1000, '2. First retrieval', 'retriever', 'aiassistant.retriever.default', 'retrieval', 0, 0, 0, 0, '', '', '', '', 'none', 0, '', 0.00, 0, 0, '', 12, 0.1500, 8, 12000, 'title,url,source_type,source_identifier', 'continue'),
(1003, 0, 0, 30, 1000, '3. Search refinement', 'query_optimizer', 'aiassistant.query_optimizer.default', 'post_retrieval', 1, 1, 1, 0, 'Rewrite the search query after the first retrieval pass. You are not an answer generator.', 'Optimize only the user search query. Use [Original User Query] and [Current Query] as the primary intent. Use [Retrieved Context] only to identify better searchable terms, acronyms, page titles or entities. Do not explain retrieved content. Do not summarize the first result. Do not answer the user question. For short acronym queries, expand the acronym only when the retrieved context strongly supports the expansion, for example: CGL TYPO3 Coding Guidelines. Keep the query in the user''s language where useful. Keep contact-related intent as a search intent only. Retrieve contact-related content only when the user explicitly asks for contact information. Do not ask for or process personal data.', 'Select concise keywords from the best matching snippets only when they improve the search. Prefer source titles, exact terms and synonyms that are likely to occur in indexed content. Ignore unrelated snippets and boilerplate. Do not copy full sentences from snippets.', 'Return exactly one improved retrieval query. No markdown, no explanation, no complete sentence answer, no JSON. Use 2 to 10 search terms where possible. If the current query is already optimal, return it unchanged.', 'last_n', 6, '', 0.00, 120, 0, '', 8, 0.0000, 6, 9000, 'title,url,source_type,source_identifier', 'continue'),
(1004, 0, 0, 40, 1000, '4. Second retrieval', 'retriever', 'aiassistant.retriever.default', 'retrieval', 0, 0, 0, 0, '', '', '', '', 'none', 0, '', 0.00, 0, 0, '', 12, 0.1200, 8, 12000, 'title,url,source_type,source_identifier', 'continue'),
(1005, 0, 0, 50, 1000, '5. Context optimizer', 'context_optimizer', 'aiassistant.context_optimizer.default', 'post_retrieval', 1, 1, 1, 0, 'Create the answer context from retrieved results.', 'Build a compact, factual answer context from the retrieval results. Keep only information that helps answer the current query. Remove duplicates, boilerplate and unrelated fragments. Separate public answer content from internal hints. Include contact-related context only when the user explicitly asks for contact information.', 'Prefer snippets with strong semantic match and useful metadata. Preserve title, URL and source identifiers where available so the frontend can present sources.', 'Return a concise context block. Include gaps or uncertainties explicitly if the retrieved material is insufficient.', 'last_n', 4, '', 0.10, 900, 0, '', 0, 0.0000, 6, 9000, 'title,url,source_type,source_identifier', 'continue'),
(1006, 0, 0, 60, 1000, '6. Answer generator', 'answer_generator', 'aiassistant.answer_generator.default', 'pre_answer', 1, 1, 1, 1, 'Generate the visible draft answer.', 'Answer the user''s question using the optimized context and the visible history. If the context does not support a claim, do not make it. If the user explicitly asks for contact information, provide only the contact details supported by the retrieved context. Do not proactively show contact details otherwise. Do not request sensitive personal data.', 'Use only the optimized answer context and stable assistant instructions. If the context is empty or insufficient, say so clearly and provide a useful fallback suggestion.', 'Write the answer for the frontend chat. Same language as user. Short paragraphs. No internal pipeline details. No raw JSON.', 'last_n', 8, '', 0.20, 900, 0, '', 0, 0.0000, 6, 9000, 'title,url,source_type,source_identifier', 'stop'),
(1007, 0, 0, 70, 1000, '7. Quality gate', 'quality_gate', 'aiassistant.quality_gate.default', 'post_answer', 1, 1, 1, 1, 'Validate and improve the final answer.', 'Check the draft answer for factual support, hallucinations, unsafe contact handling, missing uncertainty and formatting problems. If the answer claims unsupported information, remove or weaken that claim. If contact details appear, ensure they are only included when the user explicitly requested contact information, and that no sensitive personal data is requested.', 'Verify that the answer is grounded in the optimized context. Do not add new facts. Prefer a clear limitation statement over an unsupported answer.', 'Return only the final user-visible answer. No audit notes, no scoring, no JSON.', 'last_n', 4, '', 0.00, 700, 0, '', 0, 0.0000, 6, 9000, 'title,url,source_type,source_identifier', 'stop');
